USE metro_cl;

--Insertar estaciones
INSERT INTO `stations` (name) VALUES
('Tobalaba'),
('Baquedano'),
('Los Héroes'),
('Universidad de Chile'),
('Pajaritos'),
('Santa Lucía'),
('Universidad Católica'),
('Manuel Montt'),
('Pedro de Valdivia'),
('Los Leones'),
('El Golf'),
('Alcántara'),
('Escuela Militar'),
('Manquehue'),
('Hernando de Magallanes'),
('Los Dominicos'),
('Vespucio Norte'),
('Zapadores'),
('Dorsal'),
('Einstein'),
('Cementerios'),
('Plaza Chacabuco'),
('Puente Cal y Canto'),
('Santa Ana'),
('Los Héroes'),
('Toesca'),
('Parque O-Higgins'),
('Rondizzoni'),
('Franklin'),
('El Llano'),
('San Miguel'),
('Lo Vial'),
('Departamental'),
('Ciudad del Niño'),
('Lo Ovalle'),
('La Cisterna'),
('El Parrón'),
('Lo Martínez'),
('San Ramón'),
('Santa Rosa'),
('La Granja'),
('Santa Julia'),
('Vicuña Mackenna'),
('Bellavista de La Florida'),
('Mirador'),
('Pedrero'),
('San Joaquín'),
('Cerro Blanco'),
('Patronato'),
('Puente Cal y Canto'),
('Santa Ana'),
('Cumming'),
('Quinta Normal'),
('Gruta de Lourdes'),
('Blanqueado'),
('Estación Central'),
('Unión Latinoamericana'),
('Republica'),
('Los Héroes'),
('Toesca'),
('Moneda'),
('Universidad de Chile'),
('Santa Lucía'),
('Universidad Católica'),
('Baquedano'),
('Salvador'),
('Manuel Montt'),
('Pedro de Valdivia'),
('Los Leones'),
('Tobalaba'),
('El Golf'),
('Alcántara'),
('Escuela Militar'),
('Manquehue'),
('Hernando de Magallanes'),
('Los Dominicos');
